version: '2'
services:
    ledger-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/ledger/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=ledger
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
